version: 1.0.{build}

skip_commits:
  files:
    - .travis.yml
    - '**/*.md'

image:
  - Visual Studio 2019

matrix:
  fast_finish: true

install:
  - cmd: pip install conan

platform:
  - x64

configuration:
  - Debug
  - Release

build:
  parallel: true
  verbosity: minimal

before_build:
  - cmd: mkdir -p build && cd build
  - cmd: cmake -G "Visual Studio 16 2019" -A x64 ..

build_script:
  - cmd: cmake --build . --config %CONFIGURATION%

after_build:
  - cmd: ctest --extra-verbose -C %CONFIGURATION%
