name: macOS

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/windows.yml'
      - '.github/workflows/ubuntu.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/workflows/windows.yml'
      - '.github/workflows/ubuntu.yml'

jobs:
  xcode:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: [ 12.4 ]
        build_type: [ Debug, Release ]
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      JOBS: 10

    steps:
      - name: Checks out repository
        uses: actions/checkout@v2

      - name: Install Conan Package Manager
        uses: turtlebrowser/get-conan@main

      - name: CMake
        working-directory: ${{ github.workspace }}
        run: python3 cmakegen.py --build-tests

      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: cmake --build . --config ${{ matrix.build_type }} -- -j ${{ env.JOBS }}

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest --extra-verbose -C ${{ matrix.build_type }} --parallel ${{ env.JOBS }}
