name: macOS

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/windows.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/workflows/windows.yml'

jobs:
  xcode:
    runs-on: macos-10.15
    strategy:
      matrix:
        xcode: [ 12.4 ]
        build_type: [ Debug, Release ]
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      JOBS: 10

    steps:
      - uses: actions/checkout@v2

      - name: Install Conan Package Manager
        run: |
          brew install conan || brew upgrade conan

      - name: Create build directory
        working-directory: ${{ github.workspace }}
        run: mkdir -p build

      - name: CMake
        working-directory: ${{ github.workspace }}/build
        run: cmake .. -G Xcode -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: cmake --build . --config ${{ matrix.build_type }} -- -j ${{ env.JOBS }}

      - name: test
        working-directory: ${{ github.workspace }}/build
        run: ctest --extra-verbose -C ${{ matrix.build_type }} --parallel ${{ env.JOBS }}
