name: Ubuntu

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/windows.yml'
      - '.github/workflows/macos.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/workflows/windows.yml'
      - '.github/workflows/macos.yml'

jobs:
  gcc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ g++-10 ]
        build_type: [ Debug, Release ]
    env:
      JOBS: 1

    steps:
      - name: Checks out repository
        uses: actions/checkout@v2

      - name: Install Conan Package Manager
        uses: turtlebrowser/get-conan@main

      - name: CMake
        working-directory: ${{ github.workspace }}
        run: |
          mkdir -p build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DENABLE_COVERAGE=ON

      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: cmake --build . --config ${{ matrix.build_type }} -- -j ${{ env.JOBS }}

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest --extra-verbose -C ${{ matrix.build_type }} --parallel ${{ env.JOBS }}

      - name: Code Coverage
        uses: codecov/codecov-action@v2
