name: Windows

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/macos.yml'
      - '.github/workflows/ubuntu.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/workflows/macos.yml'
      - '.github/workflows/ubuntu.yml'

jobs:
  msvc2019_latest:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [ Debug, Release ]
        architecture: [ x64 ]

    steps:
      - name: Checks out repository
        uses: actions/checkout@v2

      - name: Install Conan Package Manager
        uses: turtlebrowser/get-conan@main

      - name: CMake
        working-directory: ${{ github.workspace }}
        run: python3 cmakegen.py --build-type=${{ matrix.build_type }} --build-tests

      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: cmake --build . --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest --extra-verbose -C ${{ matrix.build_type }}
