name: Windows

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/macos.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/workflows/macos.yml'

jobs:
  msvc2019_latest:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [ Debug, Release ]
        architecture: [ x64 ]

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan Package Manager
      run: |
        python3 -m pip install --upgrade pip
        pip3 install conan
        conan user

    - name: Create build directory
      working-directory: ${{ github.workspace }}
      run: mkdir -p build

    - name: CMake
      working-directory: ${{ github.workspace }}/build
      run: cmake .. -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      working-directory: ${{ github.workspace }}/build
      run: cmake --build . --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest --extra-verbose -C ${{ matrix.build_type }}
