name: Windows

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  BUILD_TYPE: Release

jobs:
  msvc2019_latest:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [ Debug, Release ]
        architecture: [ x64 ]

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan Package Manager
      run: |
        python3 -m pip install --upgrade pip
        pip3 install conan
        conan user

    - name: Create build directory
      working-directory: ${{github.workspace}}
      run: mkdir -p build && cd build

    - name: CMake
      working-directory: ${{github.workspace}}/build
      run: cmake .. -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --extra-verbose -C ${{env.BUILD_TYPE}}
